version: "3.8"

services:
  bot:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./responses:/app/responses

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
